### ISSUE TITLE
Block Weights Individually

### ISSUE THREAD

**Issue by rafstahelin** [rockerBOO/lora-inspector#11]
Is there a way to see lora block weights individually? I seem to only get noticeable weights on B8. I'd like to be able to extract the individual block weights to play with lora features on different layers. I have yet to understand why some lora's have more significant layers and others have very few if not only one

**Comment by rockerBOO** [comment]
I have block weights on my other version of this application. https://lora-inspector.rocker.boo/ . Easier to view it on the web application at this time.

![Screenshot 2023-12-15 at 04-47-26 LoRA Inspector](https://github.com/rockerBOO/lora-inspector/assets/15027/621d5365-1ab2-48db-b3bd-24c72d2b3524)

**Comment by rafstahelin** [comment]
Thanks that’s awesome. Will check it out Best, Raf On 15 Dec 2023, at 09:47, Dave Lage ***@***.***> wrote:﻿
I have block weights on my other version of this application. https://lora-inspector.rocker.boo/ . Easier to view it on the web application at this time.
Screenshot.2023-12-15.at.04-47-26.LoRA.Inspector.png (view on web)
