### ISSUE TITLE
Am I doing the right thing? xD

### ISSUE THREAD

**Issue by ghost** [rockerBOO/lora-inspector#2]
`Please submit the following keys so we can get a parser made for it: dict_keys(['sshs_model_hash', 'sshs_legacy_hash'])`

**Comment by rockerBOO** [comment]
thank you, i'll take a look.

**Comment by rockerBOO** [comment]
Should be fixed with [c6a6a096](https://github.com/rockerBOO/lora-inspector/commit/c6a6a0960b344c59e2b4d5ca97cb7b40cd2f6e4f). Thanks for letting me know!
